apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    resources:
      - group: ""
        resources: ["pods", "secrets", "configmaps"]
  - level: RequestResponse
    users: ["system:admin"]
  - level: None
    verbs: ["get"]
    resources:
      - group: ""
        resources: ["events"]
